@startuml
title CineFlow - Arquitetura Geral

left to right direction
skinparam linetype ortho
skinparam shadowing false

package "Frontend" {
  [Web SPA]
  [Mobile App]
  [Admin Panel]
}

package "Backend" {
  [API Gateway]

  [Auth Service]
  [Catalog Service]
  [Sales Service]
  [Payment Service]
  [Notification Service]
}

package "Mensageria" {
  queue "RabbitMQ / SQS"
}

package "Dados" {
  database "PostgreSQL"
  database "Redis Cache"
  database "Elasticsearch"
}

package "Cloud" {
  [Vercel]
  [Render]
  [AWS]
}

[Web SPA] --> [Vercel]
[Mobile App] --> [Vercel]
[Admin Panel] --> [Render]

[Vercel] --> [API Gateway] : HTTPS REST
[Render] --> [API Gateway] : HTTPS REST

[API Gateway] --> [Auth Service]
[API Gateway] --> [Catalog Service]
[API Gateway] --> [Sales Service]
[API Gateway] --> [Payment Service]

[Sales Service] --> "RabbitMQ / SQS"
[Notification Service] --> "RabbitMQ / SQS"

[Catalog Service] --> PostgreSQL
[Sales Service] --> PostgreSQL
[Sales Service] --> "Redis Cache"

[Catalog Service] --> Elasticsearch

[AWS] --> PostgreSQL
[AWS] --> "RabbitMQ / SQS"

@enduml