@startuml
title Modelo de Dados (Diagrama ER) - CineFlow
entity "Usuario" as U {
  *id : UUID
  nome : varchar
  email : varchar
  senha_hash : varchar
}
entity "Filme" as F {
  *id : UUID
  titulo : varchar
  descricao : text
  duracao_min : int
}
entity "Sala" as S {
  *id : UUID
  nome : varchar
  capacidade : int
}
entity "Sessao" as Se {
  *id : UUID
  filme_id : UUID
  sala_id : UUID
  inicio : datetime
  preco : decimal
}
entity "Assento" as A {
  *id : UUID
  sala_id : UUID
  linha : varchar
  numero : varchar
}
entity "Reserva" as R {
  *id : UUID
  usuario_id : UUID
  sessao_id : UUID
  data_criacao : datetime
  status : varchar
  valor : decimal
}
entity "Reserva_Assento" as RA {
  *reserva_id : UUID
  *assento_id : UUID
}
entity "Pagamento" as P {
  *id : UUID
  reserva_id : UUID
  metodo : varchar
  status : varchar
  valor : decimal
}

U ||--o{ R
F ||--o{ Se
S ||--o{ Se
Se ||--o{ A
Se ||--o{ R
R ||--o{ RA
RA }o--|| A
R ||--o{ P

@enduml
