@startuml
title Diagrama de Sequência do Sistema - Reserva (CineFlow)
actor Cliente
participant "App (Web/Mobile)" as App
participant "API Gateway / BFF" as APIGW
participant "Sales Service" as Sales
participant "Auth Service" as Auth
participant "Payment Service" as Payment
database "SalesDB" as SalesDB

Cliente -> App: Seleciona filme, sessão e assentos
App -> APIGW: POST /reservas {user, sessão, assentos}
APIGW -> Auth: Validar token/credenciais
Auth --> APIGW: Token válido
APIGW -> Sales: Criar reserva (pendente)
Sales -> SalesDB: Gravar reserva(status=PENDENTE)
Sales --> APIGW: reservaId
APIGW -> Payment: Iniciar pagamento (valor, dados cartão)
Payment --> APIGW: Pagamento aprovado
APIGW -> Sales: Atualizar reserva(status=CONFIRMADA)
Sales -> SalesDB: Atualizar status
APIGW --> App: Confirmação + e-ticket
App --> Cliente: Exibe confirmação

@enduml
